#!/usr/bin/env python3
"""Ingest Spider dataset into the text2sql vector DB.

Usage:
    python scripts/ingest_spider.py --db department_store
    python scripts/ingest_spider.py --db department_store --split test  # only train
"""

import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from t2sql.agent import get_sql_agent
from t2sql.utils import logger, parse_schema_sql


SPIDER_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "spider")


async def ingest_spider_db(
    db_name: str,
    split: str = "train",
    spider_dir: str = SPIDER_DATA_DIR,
    descriptor_path: str | None = None,
):
    """Ingest a single Spider database into the text2sql system.

    Args:
        db_name: Spider database name (e.g., "department_store").
        split: Which data split to use for training ("train" or "all").
        spider_dir: Root directory of the Spider dataset.
        descriptor_path: Optional path to descriptor config.
    """
    schema_path = os.path.join(spider_dir, "schema.sql")
    if not os.path.exists(schema_path):
        logger.error(f"Schema not found: {schema_path}")
        return

    train_file = os.path.join(spider_dir, f"{db_name}_train.json")
    if not os.path.exists(train_file):
        logger.warning(
            f"Training data not found: {train_file}, falling back to filtered train_spider"
        )
        # Fallback: filter from full train_spider.json
        full_train = os.path.join(spider_dir, "train_spider.json")
        if os.path.exists(full_train):
            with open(full_train) as f:
                all_data = json.load(f)
            train_data = [item for item in all_data if item.get("db_id") == db_name]
        else:
            train_data = []
    else:
        with open(train_file) as f:
            train_data = json.load(f)

    logger.info(f"=== Ingesting Spider DB: {db_name} ===")
    logger.info(f"Schema: {schema_path}")
    logger.info(f"Training examples: {len(train_data)}")

    # 1. Create agent
    logger.info("Creating agent...")
    agent = get_sql_agent(descriptor_path)

    # 2. Parse schema.sql → DataFrame
    logger.info("Parsing schema.sql...")
    schema_df = parse_schema_sql(schema_path, db_name=db_name)

    # 3. Train from schema: LLM generates semantic markdown → JSON → vector DB
    logger.info("Step 1/3: Generating documentation from schema...")
    await agent.train_from_schema_df(schema_df, db_name=db_name)

    # 4. Train on JSON documentation (generated by train_from_schema_df)
    logger.info("Step 2/3: Ingesting JSON documentation...")
    await agent.train_on_documentation_json()

    # 5. Learn SQL examples
    logger.info(f"Step 3/3: Learning {len(train_data)} SQL examples...")
    for i, item in enumerate(train_data):
        question = item["question"]
        sql = item["query"]
        logger.info(
            f"  [{i+1}/{len(train_data)}] Learning: {question[:60]}..."
        )
        try:
            await agent.learn_sql(question, sql)
        except Exception as e:
            logger.error(f"  Failed to learn example: {e}")

    logger.info(f"=== Done ingesting {db_name} ===")
    logger.info(f"  Tables documented: {schema_df['table_name'].nunique()}")
    logger.info(f"  SQL examples learned: {len(train_data)}")


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Ingest Spider dataset")
    parser.add_argument(
        "--db", type=str, required=True, help="Spider database name (e.g., department_store)"
    )
    parser.add_argument(
        "--split",
        type=str,
        default="train",
        choices=["train", "all"],
        help="Data split to use for training (default: train)",
    )
    parser.add_argument(
        "--spider-dir",
        type=str,
        default=SPIDER_DATA_DIR,
        help="Path to Spider dataset directory",
    )
    parser.add_argument(
        "--descriptor",
        type=str,
        default=None,
        help="Path to descriptor config (default: uses descriptors/default)",
    )

    args = parser.parse_args()
    asyncio.run(
        ingest_spider_db(
            db_name=args.db,
            split=args.split,
            spider_dir=args.spider_dir,
            descriptor_path=args.descriptor,
        )
    )


if __name__ == "__main__":
    main()